name: CI for YOLO Seg App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download models
        run: |
          mkdir -p models
          cd models
          curl -L -o yolov5s.pt https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov5s.pt
          curl -L -o yolov8n-seg.pt https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-seg.pt
          curl -L -o yolov8n-pose.pt https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-pose.pt
          python -c "import torch, torchvision.models as models; torch.save(models.resnet18(pretrained=True), 'resnet18.pt')"

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backend/ --count --show-source --statistics

      - name: Run FastAPI server health check
        run: |
          uvicorn backend.main:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/health

      - name: Run unit tests (optional)
        run: |
          pytest tests/ || echo "No tests yet"
        continue-on-error: true
